commitish: 'main'
replacers:
  - search: '/(<!.*)\s+/gm'
    replace: ''
  - search: '/\[(.*?)\]/g'
    replace: ''
  - search: '(?<=^|[\.]\s)([a-z])'
    replace: '\U$1'
change-template: '- $TITLE (#$NUMBER)$BODY'
template: |
  # Release notes
  $CHANGES
